dist: xenial

git:
  depth: false

addons:
  hosts:
    - magento2.docker

services:
  - docker

language: php

stages:
  - static-unit
  - test

jobs:
  include:
    - stage: static-unit
      script: ./tests/travis/static-unit.sh;
      php: '7.1'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.2'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.3'
      env:
        - TEST_SUITE=static-unit
    - stage: test
      php: '7.1'
      env:
        - TEST_SUITE=functional-ee
        - PART_INDEX=1
    - php: '7.1'
      env:
        - TEST_SUITE=functional-ee
        - PART_INDEX=2
    - php: '7.2'
      env:
        - TEST_SUITE=functional-ee
    - php: '7.3'
      env:
        - TEST_SUITE=functional-ee
    - php: '7.4'
      dist: bionic
      env:
        - TEST_SUITE=functional-ee
    - php: '7.1'
      env:
        - TEST_SUITE=functional-ce
        - PART_INDEX=1
    - php: '7.1'
      env:
        - TEST_SUITE=functional-ce
        - PART_INDEX=2
    - php: '7.2'
      env:
        - TEST_SUITE=functional-ce
    - php: '7.3'
      env:
        - TEST_SUITE=functional-ce
    - php: '7.4'
      dist: bionic
      env:
        - TEST_SUITE=functional-ce

before_install:
  # https://github.com/kylekatarnls/update-helper/issues/9
  - if [ -n "${COMPOSER_VERSION}" ]; then travis_retry composer self-update ${COMPOSER_VERSION}; fi;

install:
  - phpenv config-add travis.php.ini
  - composer config http-basic.repo.magento.com ${REPO_USERNAME_CE} ${REPO_PASSWORD_CE}
  - composer config github-oauth.github.com ${GITHUB_TOKEN}
  - if [ -n "${MCD_VERSION}" ] && [ $TRAVIS_PHP_VERSION != "7.0" ]; then composer config repositories.mcd git git@github.com:magento/magento-cloud-docker.git && composer require "magento/magento-cloud-docker:${MCD_VERSION}" --no-update; fi;
  - if [ -n "${MQP_VERSION}" ]; then composer config repositories.mqp git git@github.com:magento/quality-patches.git && composer require "magento/quality-patches:${MQP_VERSION}" --no-update; fi;
  - if [ -n "${MCC_VERSION}" ]; then composer config repositories.mcc git git@github.com:magento/magento-cloud-components.git && composer require "magento/magento-cloud-components:${MCC_VERSION}" --no-update; fi;
  - if [ -n "${ECE_VERSION}" ]; then composer config repositories.ece git git@github.com:magento/ece-tools.git && composer require "magento/ece-tools:${ECE_VERSION}" --no-update; fi;
  - composer config repositories.magento composer https://repo.magento.com/
  - composer require "magento/framework:*" --no-update
  - composer require "magento/module-store:*" --no-update
  - composer require "magento/module-url-rewrite:*" --no-update
  - composer update -n --no-suggest

before_script:
  - sudo sysctl -w vm.max_map_count=262144
  - if [ $TEST_SUITE == "functional-ce" ]; then cp codeception.dist.yml codeception.yml && sed -i "s/REPO_USERNAME/REPO_USERNAME_CE/" codeception.yml && sed -i "s/REPO_PASSWORD/REPO_PASSWORD_CE/" codeception.yml; fi;

script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional-ee" ]; then ./tests/travis/functional-ee.sh; fi;
  - if [ $TEST_SUITE == "functional-ce" ]; then ./tests/travis/functional-ce.sh; fi;
