dist: bionic

git:
  depth: false

addons:
  hosts:
    - magento2.docker

services:
  - docker

language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - TEST_SUITE=functional

stages:
  - static-unit
  - test

jobs:
  include:
    - stage: static-unit
      script: ./tests/travis/static-unit.sh;
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.1'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.2'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.3'
      env:
        - TEST_SUITE=static-unit
    - stage: test
      script: if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional" ]; then ./tests/travis/functional.sh; fi;
      php: '7.1'
      env:
        - TEST_SUITE=test
    - script: if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional" ]; then ./tests/travis/functional.sh; fi;
      php: '7.2'
      env:
        - TEST_SUITE=test
    - script: if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional" ]; then ./tests/travis/functional.sh; fi;
      php: '7.3'
      env:
        - TEST_SUITE=test

install: composer update
