dist: xenial

git:
  depth: false

addons:
  hosts:
    - magento2.docker

services:
  - docker

language: php

stages:
  - static-unit
  - test

jobs:
  include:
    - stage: static-unit
      script: ./tests/travis/static-unit.sh;
      php: '7.0'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.1'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.2'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.3'
      env:
        - TEST_SUITE=static-unit
    - stage: test
      php: '7.1'
      env:
        - TEST_SUITE=functional
    - php: '7.2'
      env:
        - TEST_SUITE=functional
    - php: '7.3'
      env:
        - TEST_SUITE=functional

install:
  - composer config github-oauth.github.com ${GITHUB_TOKEN}
  - if [ -n "${MCD_VERSION}" ] && [ $TRAVIS_PHP_VERSION != "7.0" ]; then composer config repositories.mcd git git@github.com:magento/magento-cloud-docker.git && composer require "magento/magento-cloud-docker:${MCD_VERSION}" --no-update; fi;
  - composer update -n --no-suggest

before_script:
  - sudo sysctl -w vm.max_map_count=262144

script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional" ]; then ./tests/travis/functional.sh; fi;
